### ISSUE TITLE
Cannot execute parse: missing test file

### ISSUE THREAD

**Issue by LucaCappelletti94** [TheJacksonLaboratory/N2V#21]
Hello everyone,

May I ask where I can find the file `small_g2d_test.txt`?

I am trying to extend the test suite and without it, I cannot run the `n2vParser` class method's `parse`.

**Comment by vidarmehr** [comment]
Dear Luca,

Here is the lines of small_g2d_test.txt:
g2972	d616202	1000.0
g6664	d615866	1000.0
g9731	d616781	1000.0
g4913	d616415	1000.0
g2549	d605428	1000.0
g79797	d616469	1000.0
g79797	d616468	1000.0
g1503	d615897	1000.0
g4043	d615431	1000.0
g10058	d609153	1000.0
g2263	d609579	1000.0
g1314	d616414	1000.0
g25885	d616462	1000.0
g10126	d616059	1000.0
g8878	d616437	1000.0
g4040	d616724	1000.0
g84823	d616540	1000.0
g84733	d613080	1000.0
g2531	d617526	1000.0
g166378	d616577	1000.0
g6513	d608885	1000.0
g136371	d603383	1000.0
g10747	d613791	1000.0
g3777	d615344	1000.0
g4882	d616255	1000.0
g79731	d616239	1000.0
g23516	d617013	1000.0
g126129	d616282	1000.0

**Comment by vidarmehr** [comment]
I also uploaded the file in test/data.

**Comment by LucaCappelletti94** [comment]
Thank you, perfect!

I have a similar issue with `g2d_association_9_2017_test` for testing the execution of `output_nodes_and_edges_test_set` and I'm guessing another file for `output_nodes_and_edges ` and `gene_protein_disease_edges`.

Could you recover also files to test these methods?

**Comment by vidarmehr** [comment]
I added g2d_associations_test_9_2017
