### ISSUE TITLE
Method `predict_links` fails on execution

### ISSUE THREAD

**Issue by LucaCappelletti94** [TheJacksonLaboratory/N2V#22]
Some methods from the class [`LinkPrediction`](https://github.com/TheJacksonLaboratory/N2V/blob/master/n2v/link_prediction.py) fail the execution in a basic example (that might be wrong) that I tried to setup in [the class test suite](https://github.com/TheJacksonLaboratory/N2V/blob/master/tests/test_link_prediction.py#L35).

The methods are:

- [`predict_links `](https://github.com/TheJacksonLaboratory/N2V/blob/b94b59940ea13992e440dd7dd769f91cc8a0c6b6/tests/test_link_prediction.py#L35)
- [`output_Logistic_Reg_results `](https://github.com/TheJacksonLaboratory/N2V/blob/b94b59940ea13992e440dd7dd769f91cc8a0c6b6/tests/test_link_prediction.py#L36)
- [`output_diagnostics_to_logfile `](https://github.com/TheJacksonLaboratory/N2V/blob/b94b59940ea13992e440dd7dd769f91cc8a0c6b6/tests/test_link_prediction.py#L37)

Are the parameters used for the example wrong?

**Comment by vidarmehr** [comment]
The parameters are wrong.
LinkPrediction(train_graph, test_graph, embedded_train_graph_path, params={}):
where parameters are edge_embedding method and portion_false_edges.

The parameters that you entered are: LinkPrediction(train, train, inputfile, params=params).
The second train, inputfile and params are wrong.

**Comment by LucaCappelletti94** [comment]
Ok, thanks! I will soon rewrite the test based on the file [`runDiseaseLinkPrediction.py`](https://github.com/TheJacksonLaboratory/N2V/blob/master/runDiseaseLinkPrediction.py), now that you have uploaded the required files.
