### ISSUE TITLE
Absolute paths in code relative to Peter's computer

### ISSUE THREAD

**Issue by LucaCappelletti94** [TheJacksonLaboratory/N2V#24]
Hello,

I was trying to base some tests on the `run*` files in the root of the repositories, and in one of them, [`runDiseaseLinkPrediction.py`](https://github.com/TheJacksonLaboratory/N2V/blob/master/runDiseaseLinkPrediction.py), there are absolute paths to some files. Are these files too big to be in the repository? How big are they? Is there an equivalent in the test repository?

- [`"/home/robinp/PycharmProjects/IDG2KG-project-management/n2v/g2d_test.txt"`](https://github.com/TheJacksonLaboratory/N2V/blob/00885d3b79f255b9d97916609b7db8caf3930e0e/runDiseaseLinkPrediction.py#L7)
- [`"/home/robinp/PycharmProjects/IDG2KG-project-management/n2v/edgelist.txt"`](https://github.com/TheJacksonLaboratory/N2V/blob/00885d3b79f255b9d97916609b7db8caf3930e0e/runDiseaseLinkPrediction.py#L11)

Another absolute path is present in [`runDiseaseGeneEmbedding.py`](https://github.com/TheJacksonLaboratory/N2V/blob/00885d3b79f255b9d97916609b7db8caf3930e0e/runDiseaseGeneEmbedding.py#L12).

**Comment by vidarmehr** [comment]
Hi Luca,

I uploaded g2d_test.txt file, but edgelist is too big to be in the repository.

**Comment by LucaCappelletti94** [comment]
Ok, could you upload a working fraction of the file? How big is the file? Maybe if compressed could get below the 100MB threshold.

Thanks!

**Comment by vidarmehr** [comment]
Yes. I uploaded edgelist.txt.zip.

**Comment by LucaCappelletti94** [comment]
Ok, now it seems like the [`"'disease.embedded'"`](https://github.com/TheJacksonLaboratory/N2V/blob/dc8ec72fa49993aa44ebe8af0181949f12931000/runDiseaseLinkPrediction.py#L18) is missing. Could you upload it, or where could I find it?

**Comment by LucaCappelletti94** [comment]
Oh I see it is rendered by the other method.

**Comment by vidarmehr** [comment]
embedded_graph is the embedding of the training graph which is obtained using Node2Vec.
