### ISSUE TITLE
 extend or append

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/N2V#32]
# should this be extend or append??  -- next_batch (SG)
            batch = np.append(batch, current_batch)
            labels = np.append(labels, current_labels, axis=0)

**Comment by LucaCappelletti94** [comment]
Generally one should not iteratively expand a NumPy array, as this can be a computational bottleneck. Where is this in the code? There might be a better solution still.

**Comment by pnrobinson** [comment]
I am working on another implementation that avoids this!
