### ISSUE TITLE
Unable to run test suite

### ISSUE THREAD

**Issue by LucaCappelletti94** [TheJacksonLaboratory/N2V#6]
Hello,

I am Luca, a PhD student from the AnacletoLab (University of Milan). I have started to take a look at the code, and I was beginning from running the present test suite.

However, it fails since it tries [to import the class `Graph` from hetnode2vec at line 6 of the file test_node2vec.py](https://github.com/TheJacksonLaboratory/N2V/blob/8b361a1a8417bb01f6da79afdcef49a220c32e76/tests/test_node2vec.py#L6)

```python
from hn2v.hetnode2vec import Graph
```

I am guessing that the class was previously called `Graph` and then afterwards changed the name to `N2vGraph`, and the test was left un-updated. I have therefore tried to replace the class but the number of parameters that the two classes accept is different.

To avoid the test suite breaking in the future I would propose using [Travis-CI](https://travis-ci.com/), which is free to use for private repositories for students and professors for research purposes. I have experience in setting up a test pipeline with Travis-CI, if required.

**Comment by pnrobinson** [comment]
seems to be working now. We are going to try and setup travis etc but this requires getting permissions set up on the JAX github (I will work on this)
